//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rizonesoft.Office.Verbum.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rizonesoft.Office.Verbum.Language.Dialogs", typeof(Dialogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Spelling.
        /// </summary>
        internal static string AutoSpellingButton_Caption {
            get {
                return ResourceManager.GetString("AutoSpellingButton_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*|All Supported Files (*.docx; *.docm; *.dotx; *.dotm; *.doc; *.dot; *.odt; *.rtf; *.htm; *.html; *.mht; *.eml; *.epub; *.xml; *.txt)|*.docx;*.docm;*.dotx;*.dotm;*.doc;*.dot;*.odt;*.rtf;*.htm;*.html;*.mht;*.eml;*.epub;*.xml;*.txt|Word 2007 Document (*.docx)|*.docx|Word Macro-Enabled Document (*.docm)|*.docm|Word Template (*.dotx)|*.dotx|Word Macro-Enabled Template (*.dotm)|*.dotm|Microsoft Word Document (*.doc)|*.doc|Word 97-2003 Template (*.dot)|*.dot|OpenDocument Text Document (*.odt)|*. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenFileFolder_Filter {
            get {
                return ResourceManager.GetString("OpenFileFolder_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Document.
        /// </summary>
        internal static string OpenFileFolder_Title {
            get {
                return ResourceManager.GetString("OpenFileFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string RibbonGroup_Common {
            get {
                return ResourceManager.GetString("RibbonGroup_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To.
        /// </summary>
        internal static string RibbonGroup_Export_To {
            get {
                return ResourceManager.GetString("RibbonGroup_Export_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string RibbonGroup_Info {
            get {
                return ResourceManager.GetString("RibbonGroup_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string RibbonGroup_Options {
            get {
                return ResourceManager.GetString("RibbonGroup_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string RibbonPage_File {
            get {
                return ResourceManager.GetString("RibbonPage_File", resourceCulture);
            }
        }
    }
}
