# These are supported funding model platforms

github: [rizonesoft] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user
custom: [Donate with PayPal](https://www.paypal.com/donate/?hosted_button_id=5FK4H8N8Y7Z7S)
