//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rizonesoft.Office.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rizonesoft.Office.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover ({0}).
        /// </summary>
        internal static string ExceptionForm_Button_Recover {
            get {
                return ResourceManager.GetString("ExceptionForm_Button_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate.
        /// </summary>
        internal static string ExceptionForm_Button_Terminate {
            get {
                return ResourceManager.GetString("ExceptionForm_Button_Terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It appears our over-caffeinated developers, in their java-induced frenzy, might have overlooked a minor detail. We get it, this isn&apos;t the perfect time for you to be playing detective. But if you can spare a moment from rolling your eyes, your assistance in pinpointing this elusive bug would mean the world to us. .
        /// </summary>
        internal static string ExceptionForm_Description {
            get {
                return ResourceManager.GetString("ExceptionForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With our unwavering commitment to your privacy, we assure you that your personal information is safe and secure. We do not gather any unnecessary data and uphold stringent measures to protect the integrity of your personal details..
        /// </summary>
        internal static string ExceptionForm_Privacy_Notice {
            get {
                return ResourceManager.GetString("ExceptionForm_Privacy_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string ExceptionForm_Title {
            get {
                return ResourceManager.GetString("ExceptionForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the midst of storing our linguistic data, we&apos;ve encountered an unanticipated glitch in the matrix. To debug this conundrum, we suggest delving into the log file&apos;s trove of information. With your help, we&apos;ll rectify the anomaly and optimize our code for seamless performance!.
        /// </summary>
        internal static string Language_CultureInfo_Error {
            get {
                return ResourceManager.GetString("Language_CultureInfo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unanticipated Glitch!.
        /// </summary>
        internal static string Language_CultureInfo_ErrorCaption {
            get {
                return ResourceManager.GetString("Language_CultureInfo_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While we were busy building the language Drop Down menu, an unexpected issue snuck in uninvited. Rest assured, our dependable log file serves as our detective, equipped with a magnifying glass, ready to uncover the root cause of this disturbance..
        /// </summary>
        internal static string Language_DropDown_Error {
            get {
                return ResourceManager.GetString("Language_DropDown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string LicenseForm_ActivateButton {
            get {
                return ResourceManager.GetString("LicenseForm_ActivateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License activated!.
        /// </summary>
        internal static string LicenseForm_Activated {
            get {
                return ResourceManager.GetString("LicenseForm_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string LicenseForm_CloseButton {
            get {
                return ResourceManager.GetString("LicenseForm_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete License.
        /// </summary>
        internal static string LicenseForm_DeleteLicense {
            get {
                return ResourceManager.GetString("LicenseForm_DeleteLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get License.
        /// </summary>
        internal static string LicenseForm_GetLicenseButton {
            get {
                return ResourceManager.GetString("LicenseForm_GetLicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, that&apos;s not even in the same neighborhood as a valid license key! If this is a joke, we&apos;re definitely missing the punchline. If it&apos;s not, our support team is ready to help you find your way..
        /// </summary>
        internal static string LicenseForm_LicenseError_Message {
            get {
                return ResourceManager.GetString("LicenseForm_LicenseError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, this is awkward... That license key doesn&apos;t seem to be on the guest list. Are you sure it&apos;s not from a cereal box or something? If you think this is a mistake, our support team is ready to sort this out..
        /// </summary>
        internal static string LicenseForm_LicenseInValid_Message {
            get {
                return ResourceManager.GetString("LicenseForm_LicenseInValid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string LicenseForm_LicenseInValid_Title {
            get {
                return ResourceManager.GetString("LicenseForm_LicenseInValid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, look at you with your fancy valid license key! You&apos;re all set to enjoy our premium features. Happy exploring!.
        /// </summary>
        internal static string LicenseForm_LicenseValid_Message {
            get {
                return ResourceManager.GetString("LicenseForm_LicenseValid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string LicenseForm_LicenseValid_Title {
            get {
                return ResourceManager.GetString("LicenseForm_LicenseValid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not activated!.
        /// </summary>
        internal static string LicenseForm_NotActivated {
            get {
                return ResourceManager.GetString("LicenseForm_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string LicenseForm_PasteButton {
            get {
                return ResourceManager.GetString("LicenseForm_PasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We greatly appreciate your continued support. We are pleased to inform you that all previously disabled features are now permanently enabled. For dedicated support, please don&apos;t hesitate to reach out to our team at &lt;a href = &quot;mailto: support@rizonetech.com&quot;&gt;support@rizonetech.com&lt;/a&gt;. We encourage you to recommend the Rizonesoft Office Suite to your colleagues and friends. Thank you for choosing us as your preferred software provider.
        ///.
        /// </summary>
        internal static string LicenseForm_ThanksLabel {
            get {
                return ResourceManager.GetString("LicenseForm_ThanksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0} {1} License Activation! Here, you can enter your license key to unlock all the fantastic features of our application. If you&apos;ve already got a key, pop it into the text box and hit &apos;Activate&apos;. If your key is valid, you&apos;ll be all set to enjoy our premium features. Don&apos;t have a license key yet?  &lt;a href=&quot;{2}&quot;&gt;Click here&lt;/a&gt; to get one..
        /// </summary>
        internal static string LicenseForm_ThanksLabel_NotRegistered {
            get {
                return ResourceManager.GetString("LicenseForm_ThanksLabel_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        internal static string LicenseForm_Title {
            get {
                return ResourceManager.GetString("LicenseForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our language data has taken a most unexpected sabbatical, leaving us in a temporary state of conversational limbo..
        /// </summary>
        internal static string LoadLanguages_Error {
            get {
                return ResourceManager.GetString("LoadLanguages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitch Detected!.
        /// </summary>
        internal static string MessageBox_Error_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string OfficeUpdate_Button {
            get {
                return ResourceManager.GetString("OfficeUpdate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock new possibilities!.
        /// </summary>
        internal static string OfficeUpdate_Caption {
            get {
                return ResourceManager.GetString("OfficeUpdate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to explore the new Rizonesoft Office version ({0}). Update available now..
        /// </summary>
        internal static string OfficeUpdate_Message {
            get {
                return ResourceManager.GetString("OfficeUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string Program_Unexpected_Error_Caption {
            get {
                return ResourceManager.GetString("Program_Unexpected_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        internal static string Program_Unexpected_Error_Message {
            get {
                return ResourceManager.GetString("Program_Unexpected_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string RibbonButtonItem_Donate {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string RibbonButtonItem_Exception {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get License.
        /// </summary>
        internal static string RibbonButtonItem_GetLicense {
            get {
                return ResourceManager.GetString("RibbonButtonItem_GetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s manual.
        /// </summary>
        internal static string RibbonButtonItem_HelpDocs {
            get {
                return ResourceManager.GetString("RibbonButtonItem_HelpDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Home.
        /// </summary>
        internal static string RibbonButtonItem_Home {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string RibbonButtonItem_License {
            get {
                return ResourceManager.GetString("RibbonButtonItem_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RibbonButtonItem_Settings {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion Board.
        /// </summary>
        internal static string RibbonButtonItem_Suggestions {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string RibbonButtonItem_Support {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string RibbonButtonItem_Update {
            get {
                return ResourceManager.GetString("RibbonButtonItem_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your generous support, big or small, will make a significant impact..
        /// </summary>
        internal static string RibbonButtonSuperTip_Donate {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press for a deliberate chaos creation.
        /// </summary>
        internal static string RibbonButtonSuperTip_Exception {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase or Acquire a New License.
        /// </summary>
        internal static string RibbonButtonSuperTip_GetLicense {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_GetLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your guide on how to efficiently use Rizonesoft Office. Find step-by-step instructions, learn about useful features, and discover valuable tips and tricks to optimize your productivity..
        /// </summary>
        internal static string RibbonButtonSuperTip_HelpDocs {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_HelpDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape the soul-sucking office life and dive headfirst into the Rizone! Click to teleport into Rizonesoft&apos;s madhouse of software sorcery, where the wizards wear code-laden capes and throw digital confetti..
        /// </summary>
        internal static string RibbonButtonSuperTip_Home {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embark on a linguistic adventure – Effortlessly switch interface languages and relish the delightful essence each one brings to your digital escapades..
        /// </summary>
        internal static string RibbonButtonSuperTip_Language {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;Learn more&lt;/a&gt;.
        /// </summary>
        internal static string RibbonButtonSuperTip_LearnMore {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and allocate your {0} {1} license.
        /// </summary>
        internal static string RibbonButtonSuperTip_License {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize Rizonesoft Office to fit your needs. Because one size does not always fit all..
        /// </summary>
        internal static string RibbonButtonSuperTip_Settings {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload your brilliant thoughts here.
        /// </summary>
        internal static string RibbonButtonSuperTip_Suggestions {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuck or confused? Click here for expert assistance to guide you through..
        /// </summary>
        internal static string RibbonButtonSuperTip_Support {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between Dark or Light Theme..
        /// </summary>
        internal static string RibbonButtonSuperTip_ToggleMode {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_ToggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock new possibilities! Be the first to explore the new Rizonesoft Office version..
        /// </summary>
        internal static string RibbonButtonSuperTip_Update {
            get {
                return ResourceManager.GetString("RibbonButtonSuperTip_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string RibbonGroup_Options {
            get {
                return ResourceManager.GetString("RibbonGroup_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string RibbonPageSupport {
            get {
                return ResourceManager.GetString("RibbonPageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string RibbonPageSupport_About {
            get {
                return ResourceManager.GetString("RibbonPageSupport_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        internal static string RibbonPageSupport_Contribute {
            get {
                return ResourceManager.GetString("RibbonPageSupport_Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string RibbonPageSupport_Debug {
            get {
                return ResourceManager.GetString("RibbonPageSupport_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string RibbonPageSupport_Discover {
            get {
                return ResourceManager.GetString("RibbonPageSupport_Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RibbonPageSupport_Registration {
            get {
                return ResourceManager.GetString("RibbonPageSupport_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string RibbonPageSupport_Update {
            get {
                return ResourceManager.GetString("RibbonPageSupport_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string SettingsForm_Accordion_Localization {
            get {
                return ResourceManager.GetString("SettingsForm_Accordion_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string SettingsForm_Accordion_Logging {
            get {
                return ResourceManager.GetString("SettingsForm_Accordion_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold your horses and ponder with caution before hitting that &apos;delete&apos; button on these log files. Be mindful that, much like a digital black hole, deletion is a point of no return; once gone, they&apos;re lost in the void forever. .
        /// </summary>
        internal static string SettingsForm_BtnCleanLog_Confirm_Message {
            get {
                return ResourceManager.GetString("SettingsForm_BtnCleanLog_Confirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Moment of Digital Reckoning!.
        /// </summary>
        internal static string SettingsForm_BtnCleanLog_Confirm_MessageTitle {
            get {
                return ResourceManager.GetString("SettingsForm_BtnCleanLog_Confirm_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wee hiccup has emerged, for the elusive log directory path is playing a game of digital hide-and-seek..
        /// </summary>
        internal static string SettingsForm_BtnOpenLog_ErrorMessage {
            get {
                return ResourceManager.GetString("SettingsForm_BtnOpenLog_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh No!.
        /// </summary>
        internal static string SettingsForm_BtnOpenLog_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("SettingsForm_BtnOpenLog_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Serilog.
        /// </summary>
        internal static string SettingsForm_Button_CleanLog {
            get {
                return ResourceManager.GetString("SettingsForm_Button_CleanLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moment has arrived to flex your digital muscles and purge the logs from the Serilog directory. But heed this friendly reminder – with such might comes a burden of accountability..
        /// </summary>
        internal static string SettingsForm_Button_CleanLog_TootlTip {
            get {
                return ResourceManager.GetString("SettingsForm_Button_CleanLog_TootlTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean the Serilog Directory.
        /// </summary>
        internal static string SettingsForm_Button_CleanLog_TootlTipTitle {
            get {
                return ResourceManager.GetString("SettingsForm_Button_CleanLog_TootlTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Serilog.
        /// </summary>
        internal static string SettingsForm_Button_OpenLog {
            get {
                return ResourceManager.GetString("SettingsForm_Button_OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venture forth, noble user, into the realm of log files, where revelations and digital wisdom await your discerning gaze..
        /// </summary>
        internal static string SettingsForm_Button_OpenLog_ToolTip {
            get {
                return ResourceManager.GetString("SettingsForm_Button_OpenLog_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Serilog Directory.
        /// </summary>
        internal static string SettingsForm_Button_OpenLog_ToolTipTitle {
            get {
                return ResourceManager.GetString("SettingsForm_Button_OpenLog_ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Interval.
        /// </summary>
        internal static string SettingsForm_Group_Rolling_Interval {
            get {
                return ResourceManager.GetString("SettingsForm_Group_Rolling_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rolling interval, a faithful timekeeper, orchestrates the cadence of new log file birth. By choosing the &apos;Day&apos; setting, you empower a diligent log file maestro to compose a fresh symphony each day – unfailingly, much like the punctual arrival of your morning cup o&apos; joe..
        /// </summary>
        internal static string SettingsForm_Group_RollingInterval_ToolTip {
            get {
                return ResourceManager.GetString("SettingsForm_Group_RollingInterval_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Rolling Interval.
        /// </summary>
        internal static string SettingsForm_Group_RollingInterval_ToolTipTitle {
            get {
                return ResourceManager.GetString("SettingsForm_Group_RollingInterval_ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Limit.
        /// </summary>
        internal static string SettingsForm_Label_File_Limit {
            get {
                return ResourceManager.GetString("SettingsForm_Label_File_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language Code:.
        /// </summary>
        internal static string SettingsForm_lblCurrCultLabel {
            get {
                return ResourceManager.GetString("SettingsForm_lblCurrCultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language:.
        /// </summary>
        internal static string SettingsForm_lblCurrLangLabel {
            get {
                return ResourceManager.GetString("SettingsForm_lblCurrLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language from the list on the right, and keep your fingers crossed that our developers did their job. If your favored tongue is amiss, fret not, for we&apos;ll soon expand our linguistic horizons to encompass it in the not-too-distant future..
        /// </summary>
        internal static string SettingsForm_lblLocalDescription {
            get {
                return ResourceManager.GetString("SettingsForm_lblLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        internal static string SettingsForm_lblSelectLanguage {
            get {
                return ResourceManager.GetString("SettingsForm_lblSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposing a cap on lingering log files keeps our digital abode spick and span. This trusty safeguard ensures we&apos;re not engulfed in a tidal wave of log file mayhem, preserving order amidst the ebb and flow of data..
        /// </summary>
        internal static string SettingsForm_LogFileLimit_ToolTip {
            get {
                return ResourceManager.GetString("SettingsForm_LogFileLimit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Limit.
        /// </summary>
        internal static string SettingsForm_LogFileLimit_ToolTipTitle {
            get {
                return ResourceManager.GetString("SettingsForm_LogFileLimit_ToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string SettingsForm_LogInterval_Day {
            get {
                return ResourceManager.GetString("SettingsForm_LogInterval_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string SettingsForm_LogInterval_Hour {
            get {
                return ResourceManager.GetString("SettingsForm_LogInterval_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite.
        /// </summary>
        internal static string SettingsForm_LogInterval_Infinite {
            get {
                return ResourceManager.GetString("SettingsForm_LogInterval_Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string SettingsForm_LogInterval_Minute {
            get {
                return ResourceManager.GetString("SettingsForm_LogInterval_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string SettingsForm_LogInterval_Month {
            get {
                return ResourceManager.GetString("SettingsForm_LogInterval_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsForm_TabNavPage_Advanced {
            get {
                return ResourceManager.GetString("SettingsForm_TabNavPage_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsForm_TabNavPage_General {
            get {
                return ResourceManager.GetString("SettingsForm_TabNavPage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsForm_Title {
            get {
                return ResourceManager.GetString("SettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading something awesome.
        /// </summary>
        internal static string SplashScreen_FooterRight {
            get {
                return ResourceManager.GetString("SplashScreen_FooterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string ThemeManager_Button_Dark_mode {
            get {
                return ResourceManager.GetString("ThemeManager_Button_Dark_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light mode.
        /// </summary>
        internal static string ThemeManager_Button_Light_mode {
            get {
                return ResourceManager.GetString("ThemeManager_Button_Light_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve stumbled upon a glitch in the matrix as our program configuration loading quest hit a bump. Worry not, we&apos;ve diligently jotted down this mischievous anomaly for posterity..
        /// </summary>
        internal static string Toast_AppDataPathError {
            get {
                return ResourceManager.GetString("Toast_AppDataPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitch in the Matrix!.
        /// </summary>
        internal static string Toast_AppDataPathError_Header {
            get {
                return ResourceManager.GetString("Toast_AppDataPathError_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string Toast_Button_Dismiss {
            get {
                return ResourceManager.GetString("Toast_Button_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string Toast_Button_LearnMore {
            get {
                return ResourceManager.GetString("Toast_Button_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve updated our language settings and injected a bit of linguistic wizardry into your Rizonesoft Office experience. To ensure that our witty wordplay and sarcastic undertones don&apos;t get lost in translation, we kindly ask you to restart any open programs..
        /// </summary>
        internal static string Toast_LanguageChanged {
            get {
                return ResourceManager.GetString("Toast_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Refresh.
        /// </summary>
        internal static string Toast_LanguageChanged_Header {
            get {
                return ResourceManager.GetString("Toast_LanguageChanged_Header", resourceCulture);
            }
        }
    }
}
