//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rizonesoft.Office.Zone.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rizonesoft.Office.Zone.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart email client designed for quick access and seamless communication experience..
        /// </summary>
        internal static string Office_Action_Description {
            get {
                return ResourceManager.GetString("Office_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication ({0}).
        /// </summary>
        internal static string Office_Action_Title {
            get {
                return ResourceManager.GetString("Office_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify warranty and repair management with a dedicated, organized system..
        /// </summary>
        internal static string Office_Assure_Description {
            get {
                return ResourceManager.GetString("Office_Assure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranties ({0}).
        /// </summary>
        internal static string Office_Assure_Title {
            get {
                return ResourceManager.GetString("Office_Assure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule appointments and organize your calendar with our user-friendly platform..
        /// </summary>
        internal static string Office_Booking_Description {
            get {
                return ResourceManager.GetString("Office_Booking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments ({0}).
        /// </summary>
        internal static string Office_Booking_Title {
            get {
                return ResourceManager.GetString("Office_Booking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master your time with an all-in-one time, timer, and alarm management program..
        /// </summary>
        internal static string Office_Clock_Description {
            get {
                return ResourceManager.GetString("Office_Clock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ({0}).
        /// </summary>
        internal static string Office_Clock_Title {
            get {
                return ResourceManager.GetString("Office_Clock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate and store physical document copies with efficient copying tool..
        /// </summary>
        internal static string Office_Duplicare_Description {
            get {
                return ResourceManager.GetString("Office_Duplicare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Copy ({0}).
        /// </summary>
        internal static string Office_Duplicare_Title {
            get {
                return ResourceManager.GetString("Office_Duplicare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze data, perform calculations, and create charts using robust formulas..
        /// </summary>
        internal static string Office_Evaluate_Description {
            get {
                return ResourceManager.GetString("Office_Evaluate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheets ({0}).
        /// </summary>
        internal static string Office_Evaluate_Title {
            get {
                return ResourceManager.GetString("Office_Evaluate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiently organize, access, and manage your digital files and directories..
        /// </summary>
        internal static string Office_Filer_Description {
            get {
                return ResourceManager.GetString("Office_Filer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager ({0}).
        /// </summary>
        internal static string Office_Filer_Title {
            get {
                return ResourceManager.GetString("Office_Filer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and visualize complex ideas with flowcharts, mind maps, and diagrams..
        /// </summary>
        internal static string Office_Flow_Description {
            get {
                return ResourceManager.GetString("Office_Flow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams ({0}).
        /// </summary>
        internal static string Office_Flow_Title {
            get {
                return ResourceManager.GetString("Office_Flow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover locations, plan routes, and explore geographic data with detailed maps..
        /// </summary>
        internal static string Office_Globe_Description {
            get {
                return ResourceManager.GetString("Office_Globe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps Viewer ({0}).
        /// </summary>
        internal static string Office_Globe_Title {
            get {
                return ResourceManager.GetString("Office_Globe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accurate asset tracking for improved inventory management and financial control..
        /// </summary>
        internal static string Office_Have_Description {
            get {
                return ResourceManager.GetString("Office_Have_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset tracking ({0}).
        /// </summary>
        internal static string Office_Have_Title {
            get {
                return ResourceManager.GetString("Office_Have_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represent and interpret data using interactive charts, graphs, and visualizations..
        /// </summary>
        internal static string Office_Imagine_Description {
            get {
                return ResourceManager.GetString("Office_Imagine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Visualizer ({0}).
        /// </summary>
        internal static string Office_Imagine_Title {
            get {
                return ResourceManager.GetString("Office_Imagine_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access and explore websites securely with enhanced speed and performance..
        /// </summary>
        internal static string Office_Jupiter_Description {
            get {
                return ResourceManager.GetString("Office_Jupiter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser ({0}).
        /// </summary>
        internal static string Office_Jupiter_Title {
            get {
                return ResourceManager.GetString("Office_Jupiter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, organize, and track personal or professional tasks with prioritization, deadlines, and progress tracking..
        /// </summary>
        internal static string Office_Komplete_Description {
            get {
                return ResourceManager.GetString("Office_Komplete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks ({0}).
        /// </summary>
        internal static string Office_Komplete_Title {
            get {
                return ResourceManager.GetString("Office_Komplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost sales and customer relationships with our feature-rich CRM software..
        /// </summary>
        internal static string Office_Lead_Description {
            get {
                return ResourceManager.GetString("Office_Lead_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM ({0}).
        /// </summary>
        internal static string Office_Lead_Title {
            get {
                return ResourceManager.GetString("Office_Lead_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your retail business effortlessly with our advanced POS system..
        /// </summary>
        internal static string Office_Merchant_Description {
            get {
                return ResourceManager.GetString("Office_Merchant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sale ({0}).
        /// </summary>
        internal static string Office_Merchant_Title {
            get {
                return ResourceManager.GetString("Office_Merchant_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-powered assistant with natural language processing..
        /// </summary>
        internal static string Office_Mia_Description {
            get {
                return ResourceManager.GetString("Office_Mia_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Chat ({0}).
        /// </summary>
        internal static string Office_Mia_Title {
            get {
                return ResourceManager.GetString("Office_Mia_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate tasks, track progress, and collaborate with team members efficiently..
        /// </summary>
        internal static string Office_Mission_Description {
            get {
                return ResourceManager.GetString("Office_Mission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager ({0}).
        /// </summary>
        internal static string Office_Mission_Title {
            get {
                return ResourceManager.GetString("Office_Mission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize artificial intelligence for optimized search, content discovery, and personalization..
        /// </summary>
        internal static string Office_Nerve_Description {
            get {
                return ResourceManager.GetString("Office_Nerve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Browser ({0}).
        /// </summary>
        internal static string Office_Nerve_Title {
            get {
                return ResourceManager.GetString("Office_Nerve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor and optimize work hours with our intuitive time tracking solution..
        /// </summary>
        internal static string Office_Operate_Description {
            get {
                return ResourceManager.GetString("Office_Operate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking ({0}).
        /// </summary>
        internal static string Office_Operate_Title {
            get {
                return ResourceManager.GetString("Office_Operate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize, store, and share documents using a versatile scanning solution..
        /// </summary>
        internal static string Office_Qapture_Description {
            get {
                return ResourceManager.GetString("Office_Qapture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning and OCR ({0}).
        /// </summary>
        internal static string Office_Qapture_Title {
            get {
                return ResourceManager.GetString("Office_Qapture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover lost memories by easily restoring deleted images with our tool..
        /// </summary>
        internal static string Office_Repo_Description {
            get {
                return ResourceManager.GetString("Office_Repo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover photos ({0}).
        /// </summary>
        internal static string Office_Repo_Title {
            get {
                return ResourceManager.GetString("Office_Repo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, modify, annotate, and sign PDF documents with a comprehensive set of tools..
        /// </summary>
        internal static string Office_Scholar_Description {
            get {
                return ResourceManager.GetString("Office_Scholar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF ({0}).
        /// </summary>
        internal static string Office_Scholar_Title {
            get {
                return ResourceManager.GetString("Office_Scholar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage appointments, events, and deadlines with customizable views and reminders..
        /// </summary>
        internal static string Office_Session_Description {
            get {
                return ResourceManager.GetString("Office_Session_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling ({0}).
        /// </summary>
        internal static string Office_Session_Title {
            get {
                return ResourceManager.GetString("Office_Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your computer running smoothly with our efficient cleaner..
        /// </summary>
        internal static string Office_Soap_Description {
            get {
                return ResourceManager.GetString("Office_Soap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaner ({0}).
        /// </summary>
        internal static string Office_Soap_Title {
            get {
                return ResourceManager.GetString("Office_Soap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, edit, and format documents with advanced text tools and features..
        /// </summary>
        internal static string Office_Verbum_Description {
            get {
                return ResourceManager.GetString("Office_Verbum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Processor ({0}).
        /// </summary>
        internal static string Office_Verbum_Title {
            get {
                return ResourceManager.GetString("Office_Verbum_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert written text into spoken words with realistic voices and customizable settings..
        /// </summary>
        internal static string Office_Voice_Description {
            get {
                return ResourceManager.GetString("Office_Voice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speech ({0}).
        /// </summary>
        internal static string Office_Voice_Title {
            get {
                return ResourceManager.GetString("Office_Voice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamline invoicing and billing processes with our easy-to-use financial tool..
        /// </summary>
        internal static string Office_Wealth_Description {
            get {
                return ResourceManager.GetString("Office_Wealth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing ({0}).
        /// </summary>
        internal static string Office_Wealth_Title {
            get {
                return ResourceManager.GetString("Office_Wealth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive image viewer and editor, perfect for photographers..
        /// </summary>
        internal static string Office_Xhibit_Description {
            get {
                return ResourceManager.GetString("Office_Xhibit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photos ({0}).
        /// </summary>
        internal static string Office_Xhibit_Title {
            get {
                return ResourceManager.GetString("Office_Xhibit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted email marketing campaigns to grow your audience and drive engagement..
        /// </summary>
        internal static string Office_Yield_Description {
            get {
                return ResourceManager.GetString("Office_Yield_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail marketing ({0}).
        /// </summary>
        internal static string Office_Yield_Title {
            get {
                return ResourceManager.GetString("Office_Yield_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Desktop Shortcut.
        /// </summary>
        internal static string ProgramCardControl_OffText {
            get {
                return ResourceManager.GetString("ProgramCardControl_OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Desktop Shortcut.
        /// </summary>
        internal static string ProgramCardControl_OnText {
            get {
                return ResourceManager.GetString("ProgramCardControl_OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string RibbonGroup_Options {
            get {
                return ResourceManager.GetString("RibbonGroup_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string RibbonGroup_Programs {
            get {
                return ResourceManager.GetString("RibbonGroup_Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string RibbonPage_Home {
            get {
                return ResourceManager.GetString("RibbonPage_Home", resourceCulture);
            }
        }
    }
}
